stages:
  - build
  - mirror

variables:
  NEXTCLOUD_VERSION: '32.0.11' # https://github.com/nextcloud/server/releases
  CALENDAR_VERSION: '6.4.2' # https://apps.nextcloud.com/apps/calendar
  CONTACTS_VERSION: '8.3.12' # https://apps.nextcloud.com/apps/contacts
  CHECKSUM_VERSION: '2.0.3' # https://apps.nextcloud.com/apps/checksum
  GROUP_FOLDERS_VERSION: '20.1.14' # https://apps.nextcloud.com/apps/groupfolders
  NOTIFY_PUSH_VERSION: '1.3.3' # https://apps.nextcloud.com/apps/notify_push

distributives:
  stage: build
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: never
    - when: on_success
  image: public.ecr.aws/docker/library/debian:trixie-slim
  variables:
    GIT_STRATEGY: none
  script:
    - echo 'Updating and installing required system packages and dependencies'
    - apt -qq update
    - apt install -qq -y wget

    - mkdir -p dist

    - echo "Downloading Calendar app ${CALENDAR_VERSION}"
    - wget -nv "https://github.com/nextcloud-releases/calendar/releases/download/v${CALENDAR_VERSION}/calendar-v${CALENDAR_VERSION}.tar.gz"
    - tar -zxf "calendar-v${CALENDAR_VERSION}.tar.gz" -C dist/

    - echo "Downloading Contacts app ${CONTACTS_VERSION}"
    - wget -nv "https://github.com/nextcloud-releases/contacts/releases/download/v${CONTACTS_VERSION}/contacts-v${CONTACTS_VERSION}.tar.gz"
    - tar -zxf "contacts-v${CONTACTS_VERSION}.tar.gz" -C dist/

    - echo "Downloading Checksum app ${CHECKSUM_VERSION}"
    - wget -nv "https://github.com/westberliner/checksum/releases/download/v${CHECKSUM_VERSION}/checksum.tar.gz"
    - tar -zxf "checksum.tar.gz" -C dist/

    - echo "Downloading Group Folders app ${GROUP_FOLDERS_VERSION}"
    - wget -nv "https://github.com/nextcloud-releases/groupfolders/releases/download/v${GROUP_FOLDERS_VERSION}/groupfolders-v${GROUP_FOLDERS_VERSION}.tar.gz"
    - tar -zxf "groupfolders-v${GROUP_FOLDERS_VERSION}.tar.gz" -C dist/

    - echo "Downloading Notify Push app ${NOTIFY_PUSH_VERSION}"
    - wget -nv "https://github.com/nextcloud-releases/notify_push/releases/download/v${NOTIFY_PUSH_VERSION}/notify_push-v${NOTIFY_PUSH_VERSION}.tar.gz"
    - tar -zxf "notify_push-v${NOTIFY_PUSH_VERSION}.tar.gz" -C dist/
  artifacts:
    paths:
      - dist

images:
  stage: build
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      when: never
    - when: on_success
  needs:
    - distributives
  dependencies:
    - distributives
  image: quay.io/buildah/stable:v1.43.1
  variables:
    STORAGE_DRIVER: 'vfs'
  script:
    - echo "$CI_REGISTRY_PASSWORD" | buildah login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
    - buildah build -t "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME"
        --build-arg NEXTCLOUD_VERSION="$NEXTCLOUD_VERSION"
    - buildah push "$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME"

mirror-git-github:
  stage: mirror
  rules:
    - if: $CI_PIPELINE_SOURCE == 'push'
  dependencies: []
  image: docker.io/alpine/git:v2.52.0
  variables:
    GIT_STRATEGY: clone
  script:
    - git remote add github "https://$GITHUB_USER:$GITHUB_PASSWORD@github.com/flakybitnet/nextcloud-oci.git"
    - if [ -n "${CI_COMMIT_BRANCH-}" ]; then
        git checkout -b "$CI_COMMIT_BRANCH";
        git fetch github;
        git push --force-with-lease github "$CI_COMMIT_BRANCH";
        fi
    - if [ -n "${CI_COMMIT_TAG-}" ]; then
        git push github tag $CI_COMMIT_TAG;
        fi

mirror-image-github:
  stage: mirror
  rules:
    - if: $CI_COMMIT_TAG
  dependencies: []
  image: public.ecr.aws/flakybitnet/skopeo:1.22.2-fb1
  variables:
    REGISTRY: ghcr.io
    IMAGE: flakybitnet/nextcloud-server
    GIT_STRATEGY: none
  script:
    - echo "$GITHUB_PASSWORD" | skopeo login -u "$GITHUB_USER" --password-stdin "$REGISTRY"
    - skopeo copy "docker://$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME" "docker://$REGISTRY/$IMAGE:$CI_COMMIT_REF_NAME"

mirror-image-quay:
  stage: mirror
  rules:
    - if: $CI_COMMIT_TAG
  dependencies: []
  image: public.ecr.aws/flakybitnet/skopeo:1.22.2-fb1
  variables:
    REGISTRY: quay.io
    IMAGE: flakybitnet/nextcloud-server
    GIT_STRATEGY: none
  script:
    - echo "$QUAY_PASSWORD" | skopeo login -u "$QUAY_USER" --password-stdin "$REGISTRY"
    - skopeo copy "docker://$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME" "docker://$REGISTRY/$IMAGE:$CI_COMMIT_REF_NAME"

mirror-image-amazon:
  stage: mirror
  rules:
    - if: $CI_COMMIT_TAG
  dependencies: []
  image: public.ecr.aws/flakybitnet/skopeo:1.22.2-fb1
  variables:
    REGISTRY: public.ecr.aws
    IMAGE: flakybitnet/nextcloud/server
    GIT_STRATEGY: none
    AWS_ACCESS_KEY_ID: $ECR_USER
    AWS_SECRET_ACCESS_KEY: $ECR_PASSWORD
  script:
    - printf '{"credHelpers":{"%s":"%s"}}' "$REGISTRY" 'ecr-login' > "$HOME/auth.json"
    - skopeo copy "docker://$CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME" "docker://$REGISTRY/$IMAGE:$CI_COMMIT_REF_NAME"
        --dest-authfile="$HOME/auth.json"
